### ISSUE TITLE
有可能把 移远（高通）5Gnr-QMI 也加到加速里面吗？

### ISSUE THREAD

**Issue by gsmantenna** [ptpt52/natflow#10]
现在 MTK7621 -USB3.0 - 移远的 RM500Q 5Gnr 跑流最多只能跑300M 左右， CPU 占用严重（有3个u 占用70%以上） ，有可能把这部分也加到加速里面吗？

**Comment by ptpt52** [comment]
无需处理，对任何网口都有加速。

**Comment by padavanonly** [comment]
有效果吗？

**Comment by gsmantenna** [comment]
MBIM  模式下 速度有很大提升， QMI 模式不行

**Comment by guoqiang13** [comment]
@gsmantenna ECM模式下有加速效果吗？
