### ISSUE TITLE
lan口无法启动

### ISSUE THREAD

**Issue by aptx17** [ptpt52/natflow#18]
最近更新至[d55726f] lan口灯不亮丢失无法启动，截至至0526a3c是ok的。
r2s，双网口，是不是改成针对单网口单臂路由的了？

**Comment by ptpt52** [comment]
natflow一般与硬件无关，lan口灯不亮跟natflow无关的呀

**Comment by aptx17** [comment]
> natflow一般与硬件无关，lan口灯不亮跟natflow无关的呀

也不能说灯不亮，确切的是断电重启后eth1 lan口无法启动，失去连接，暂时先回退至0526a3c了。

**Comment by aptx17** [comment]
https://github.com/ptpt52/natflow/commit/927014482c483384325a521f6e5d75ca9775a1f6
这个commit解决了。
