### ISSUE TITLE
Options to work on x86 system

### ISSUE THREAD

**Issue by micron10** [ptpt52/natflow#4]
Hi @ptpt52 
is this module will work on x86 system with Intel cpu and Intel 10G card ?

if it work how to check how its work i build module and insmod in system .

and how to limit traffic by ip

m.

**Comment by ptpt52** [comment]
1. works on x86
2. use the x-wrt fork or see here how to build for openwrt https://github.com/x-wrt/com.x-wrt/tree/master/natflow
3. fow now no way to limit traffic, but traffic rate is now readable

**Comment by micron10** [comment]
now i build and work

try to add tc  qdisc for traffic limit but not succes.

i try with pppoe client and traffic is move from ppp0 to eth1 

before load modul traffic and shaper is set on ppp0

do you have telegram

**Comment by ptpt52** [comment]
sure for pppoe traffic stats on eth1 not ppp0 if run fastpath

**Comment by ptpt52** [comment]
you may join here first: https://t.me/joinchat/IHqn_Rbk19VOfYQ1GZvKsw

**Comment by micron10** [comment]
Join thanks!
